network.host: 0.0.0.0
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.watcher.enabled: false
xpack.graph.enabled: false
path:
   logs: /usr/share/elasticsearch/logs
   data: /usr/share/elasticsearch/data
   repo: /usr/share/elasticsearch/snapshots
cluster:
   name: ${HOSTNAME}-cluster
node:
   name: ${HOSTNAME}
http:
   cors:
      enabled:        true
      allow-origin:   '*'
