version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: check-api
    ports:
      - 3000:3000
      - 6379:6379
    links:
      - elasticsearch
      - postgres
      - pender
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  pender:
    build: pender
    ports:
      - 3200:3200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  web:
    build: bridge-web
    ports:
      - 3333:3333
    links:
      - api
    volumes:
      - ./bridge-web:/app
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
