version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch:6.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: check-api
    ports:
      - 3000:3000
      - 6379:6379
      - 9333:9333
    links:
      - elasticsearch
      - postgres
      - pender
      - alegre
      - reader
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  pender:
    build: pender
    shm_size: 1G
    ports:
      - 3200:3200
      - 9555:9555
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  web:
    build: check-web
    ports:
      - 3333:3333
    links:
      - api
    volumes:
      - ./check-web:/app
      - ./check-api:/api
      - /app/node_modules
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: development
  alegre:
    build: alegre
    ports:
      - 3100:3100
    volumes:
      - ./alegre:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3100
    links:
      - elasticsearch
  reader:
    build: bridge-reader
    ports:
      - 3400:3400
      - 9222:9222
    volumes:
      - ./bridge-reader:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3400
