version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api.test:
    build: check-api
    ports:
      - 13000:13000
    links:
      - elasticsearch
      - postgres
      - pender.test
      - alegre.test
      - reader.test
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13000
  pender.test:
    build: pender
    ports:
      - 13200:13200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13200
  alegre.test:
    build: alegre
    ports:
      - 13100:13100
    volumes:
      - ./alegre:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13100
    links:
      - elasticsearch
  reader.test:
    build: bridge-reader
    ports:
      - 13400:13400
      - 9222:9222
    volumes:
      - ./bridge-reader:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13400
  web.test:
    build: check-web
    ports:
      - 13333:13333
    links:
      - api.test
      - chromedriver
    volumes:
      - ./check-web:/app
      - ./check-api:/api
      - /app/node_modules
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 13333
  chromedriver:
    build: chromedriver
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      no_proxy: 'localhost'
      HUB_ENV_no_proxy: 'localhost'
