version: '2'

volumes:
  esdata:
  pgdata:

services:
  elasticsearch:
    image: meedan/elasticsearch:6.3
    environment:
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "esdata:/usr/share/elasticsearch/data"
  postgres:
    image: postgres:9.6
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./postgresql.conf:/etc/postgresql.conf"
      - "pgdata:/var/lib/postgresql/data"
  api.test:
    build: check-api
    ports:
      - "13000:13000"
    links:
      - elasticsearch
      - postgres
      - pender.test
    volumes:
      - "./check-api:/app"
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13000
  pender.test:
    build: pender
    ports:
      - "13200:13200"
    volumes:
      - "./pender:/app"
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13200
  web.test:
    build: check-web
    ports:
      - "13333:13333"
    links:
      - api.test
      - chromedriver
    volumes:
      - "./check-web:/app"
      - "./check-api:/api"
      - "/app/node_modules"
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 13333
      MODE: test
  chromedriver:
    build: chromedriver
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      no_proxy: localhost
      HUB_ENV_no_proxy: localhost
    volumes:
      - "./check-mark:/app"
      - "./check-web/test/spec/test.png:/app/test/spec/test.png"
  alegre.test:
    build: alegre
    ports:
      - "13100:13100"
    volumes:
      - "./alegre:/app"
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13100
    links:
      - elasticsearch
  reader.test:
    build: bridge-reader
    ports:
      - "13400:13400"
      - "9222:9222"
    volumes:
      - "./bridge-reader:/app"
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13400
